name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 4.0.0-alpha-5

      - name: Build with Maven
        run: mvn clean compile package -DskipTests 

      - name: Transfer Docker image to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.IPV4_EC2 }}
          username: ${{ secrets.AWS_ACCESS_KEY }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: "./target/demo-0.0.1-SNAPSHOT.jar"
          target: /home/ubuntu/my-app

      - name: SSH into EC2 and run Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IPV4_EC2 }}
          username: ${{ secrets.AWS_ACCESS_KEY }}
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /home/ubuntu/my-app/target
            if sudo lsof -Pi :8060 -sTCP:LISTEN -t >/dev/null ; then
              sudo kill $(sudo lsof -t -i:8060) || true
            fi
            nohup java -jar demo-0.0.1-SNAPSHOT.jar > build.log 2>&1 &
